"""empty message

Revision ID: 79245af581b2
Revises: 
Create Date: 2020-07-17 16:35:25.666379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79245af581b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VEHICLE_DETAILS',
    sa.Column('VEHICLE_TAG_NUM', sa.VARCHAR(), nullable=False),
    sa.Column('VEHICLE_MAKE', sa.VARCHAR(), nullable=True),
    sa.Column('VEHICLE_MODEL', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('VEHICLE_TAG_NUM')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VEHICLE_DETAILS')
    # ### end Alembic commands ###
